// Generates tokens/tokens.css from tokens/tokens.json. Dependency-free.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const t = JSON.parse(readFileSync(join(root, "tokens/tokens.json"), "utf8"));

const groups = [
  ["color", "color"],
  ["gradient", "gradient"],
  ["radius", "radius"],
  ["space", "space"],
  ["effect", ""],
];

const lines = [":root {"];
for (const [group, prefix] of groups) {
  const set = t[group];
  if (!set) continue;
  lines.push(`  /* ${group} */`);
  for (const [key, value] of Object.entries(set)) {
    const name = prefix ? `--${prefix}-${key}` : `--${key}`;
    lines.push(`  ${name}: ${value};`);
  }
}
lines.push("}");

const header =
  "/* GENERATED by scripts/build-tokens.mjs from tokens/tokens.json. Do not edit by hand. */\n";
writeFileSync(join(root, "tokens/tokens.css"), header + lines.join("\n") + "\n");
console.log("tokens.css generated");
