// Generates tokens/tokens.css from tokens/tokens.json.
// Dependency-free so it runs anywhere. Swap in Style Dictionary later
// if your tokens originate from Figma and need richer transforms.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(readFileSync(join(root, "tokens/tokens.json"), "utf8"));

const lines = [":root {"];
for (const [group, prefix] of [["color", "color"], ["radius", "radius"], ["space", "space"]]) {
  const set = tokens[group];
  if (!set) continue;
  lines.push(`  /* ${group} */`);
  for (const [key, value] of Object.entries(set)) {
    lines.push(`  --${prefix}-${key}: ${value};`);
  }
}
lines.push("}");

const header =
  "/* GENERATED by scripts/build-tokens.mjs from tokens/tokens.json. Do not edit by hand. */\n";
writeFileSync(join(root, "tokens/tokens.css"), header + lines.join("\n") + "\n");
console.log("tokens.css generated from tokens.json");
